CREATE TABLE IF NOT EXISTS pgn (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event TEXT NOT NULL,
    site TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT,
    round TEXT NOT NULL,
    white TEXT NOT NULL,
    black TEXT NOT NULL,
    result TEXT NOT NULL,
    annotator TEXT,
    timeControl TEXT,
    whiteTimeLeft TEXT,
    blackTimeLeft TEXT,
    clockType TEXT,
    timerIncrement TEXT,
    setUp TEXT,
    fen TEXT,
    termination TEXT,
    whiteAi TEXT,
    whiteLevel TEXT,
    blackAi TEXT,
    blackLevel TEXT
)
