USE learnifyDB;

/* CREATE AN ACCOUNTs*/
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("admin", "admin", "admin", "ADMIN", "admin" );
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("proffessor", "proffessor", "proffessor", "PROFFESSOR", "proffessor" );
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("student", "student", "student", "STUDENT", "student" );
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("decan", "decan", "decan", "DECAN", "decan" );

INSERT IGNORE INTO SUBJECT(STARTDATE,NAME,PROFFESSOR_LOGIN_OID, ID) VALUES ("2023-01-01", "sistemas", "proffessor", "0");
INSERT IGNORE INTO SUBJECT(STARTDATE,NAME,PROFFESSOR_LOGIN_OID, ID) VALUES ("2023-01-02", "procesos", "proffessor", "1");
INSERT IGNORE INTO SUBJECT(STARTDATE,NAME,PROFFESSOR_LOGIN_OID, ID) VALUES ("2023-01-02", "electronica", "proffessor", "2");

INSERT IGNORE INTO SCORE(SUBJECT_ID_OID,STUDENT_LOGIN_OID,SCORE, ID) VALUES ("sistemas", "student", "9.0", "0");
INSERT IGNORE INTO SCORE(SUBJECT_ID_OID,STUDENT_LOGIN_OID,SCORE, ID) VALUES ("procesos", "student", "1.0", "1");
