USE learnifyDB;

/* CREATE AN ACCOUNTs*/
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("admin", "admin", "admin", "ADMIN", "admin" );
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("professor", "professor", "professor", "PROFESSOR", "professor" );
INSERT IGNORE INTO USER(LOGIN,NAME,PASSWORD, ROLE, SURNAME) VALUES ("student", "student", "student", "STUDENT", "student" );
INSERT IGNORE INTO SUBJECT(STARTDATE,NAME,PROFESSOR_LOGIN_OID, ID) VALUES ("2023-01-01", "sistemas", "professor", "0000");
INSERT IGNORE INTO SCORE(SUBJECT_ID_OID,STUDENT_LOGIN_OID,SCORE, ID) VALUES ("sistemas", "student", "9.0", "0000");